<?php
	/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */

$sector = $iterator = 1;
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');

/* @package Cafedu_Theme */

?>
<div class="page-container">
	<div class="product-row-container">
		<?php if (!$_productCollection->count()): ?>
    	<div class="message info empty">
    		<div>
    			<?php echo __('We can\'t find products matching the selection.') ?>
    		</div>
    	</div>
		<?php else: ?>
    	<div class="products wrapper grid products-grid">
    	<?php
		    if ($block->getMode() == 'grid') {
	        $viewMode = 'grid';
	        $image = 'category_page_grid';
		    } else {
	        $viewMode = 'list';
	        $image = 'category_page_list';
		    }
		    $pos = $block->getPositioned();
        foreach ($_productCollection as $_product):
          echo ( $iterator == 1 ) ? '<ol class="products list items product-items">' : '' ; 
      ?>				
          <?php $maxIterator = 5; ?>
          <!-- each item into html -->
          <li id="cdc-product-<?php echo $_product->getId(); ?>" class="item product product-item">
            <div class="product-item-info" data-container="product-grid">
              <a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo">
                <?php
                  $productImage = $block->getImage($_product, $image);
                  if ($pos != null) {
                    $position = ' style="left:' . $productImage->getWidth() . 'px;' . 'top:' . $productImage->getHeight() . 'px;"';
                  }
                  echo $productImage->toHtml();
                ?>
              </a>
            </div>
            <div class="product details product-item-details">
              <strong class="product name product-item-name">
                <a class="product-item-link" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getName() ?>">
                  <?php
                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                    echo $_helper->productAttribute($_product, $_product->getName(), 'name');
                  ?>
                </a>
              </strong>
              <div class="product-description"><?php echo $_product->getTitle2ndLine(); ?></div>
              <div class="product-color"><?php echo $_product->getTitle3rdLine(); ?></div>
      			  <?php if($_product->getTypeId() != 'mageworx_giftcards'):  ?>
      				  <?= $block->getProductPrice($_product); ?>
      			  <?php endif; ?>
            </div>
          </li>
          <!-- iterator and sector selection -->
          <?php 
            if( $iterator == $maxIterator || $iterator == count($_productCollection) ) {
              echo '</ol>';
              $iterator = 1;
              $sector++;
            } else {
              $iterator++;
            }
          ?>
      <?php endforeach; ?>
      </div>
    <?php endif; ?>
	</div>
</div>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {}
        }
    }
    </script>
<?php endif; ?>
