<script>
require([
	'jquery',
	'responsivetabs'
], function($){
	var cafedusizeTabs = setInterval( function () {
		if ( document.readyState !== 'complete' ) return;
    	clearInterval( cafedusizeTabs );

	    $('.size-tab').easyResponsiveTabs({
	        type: 'default',
	        width: 'auto',
	        fit: true,
	        tabidentify: 'hor_1'
	    });	
		function scrollNav() {
		  $('.size-map li a').click(function(){  
			//Toggle Class
			$(".active").removeClass("active");      
			$(this).closest('li').addClass("active");
			var theClass = $(this).attr("class");
			$('.'+theClass).parent('li').addClass('active');
			//Animate
			$('html, body').stop().animate({
				scrollTop: $( $(this).attr('href') ).offset().top - 140
			}, 400);
			return false;
		  });
		  $('.scrollTop a').scrollTop();
		}
		scrollNav();
	}, 2000 );
});
</script>
	