<div id="forgotpasswordPopup" data-bind="scope:'forgotpasswordcomponent'" style="display:none;">
  <!-- ko template: getTemplate() --><!-- /ko -->
  <script>
    window.forgotPassword = <?= \Zend_Json::encode($block->getForgotPasswordConfig()); ?>;
  </script>
  <script type="text/x-magento-init">
    {
      "#createacccountPopup": {
        "Magento_Ui/js/core/app": <?= $block->getJsLayout();?>
      }
    }
  </script>
</div>